{{ config(
    materialized='table'
) }}

SELECT 
    ID,
    INVOICE_NO,
    STOCK_CODE,
    DESCRIPTION,
    CAST(QUANTITY AS INTEGER) AS QUANTITY,
    TO_TIMESTAMP(INVOICE_DATE, 'YYYY-MM-DD HH24:MI:SS')::TIMESTAMP WITHOUT TIME ZONE AS invoice_datetime,
    CAST(UNIT_PRICE AS FLOAT) AS UNIT_PRICE,
    CUSTOMER_ID,
    COUNTRY
FROM {{ source('public', 'online_retail2') }} AS OR2
WHERE INVOICE_NO NOT ILIKE '%c%'
AND CAST(QUANTITY AS INTEGER) > 0
AND CAST(UNIT_PRICE AS FLOAT) > 0
AND CUSTOMER_ID IS NOT NULL
